### ISSUE TITLE
Fails to load when starting

### ISSUE THREAD

**Issue by Vatac** [TudbuT/ProjectorBotV2_full#1]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!
https://discord.com/api/oauth2/authorize?client_id=558050163948519453&permissions=8&scope=bot
Converting to raw frames...

**Comment by TudbuT** [comment]
This is a known issue on windows. Try [projbotv3](https://github.com/tudbut/projbotv3) or use WSL. 
(This was already fixed in DMs on Discord)
