### ISSUE TITLE
Converting for hours

### ISSUE THREAD

**Issue by N4N001** [TudbuT/ProjectorBotV2_full#2]
It still keeps saying "converting to raw frames" after few hours of converting. I looked into the files and the vid folder seems to be finished, but there is no audio files or idk if there should be any, but it keeps converting and doesn't want to finish. Restarting doesn't help either.

**Comment by TudbuT** [comment]
This issue was fixed in [version 3](https://github.com/tudbut/projbotv3). It's a pretty very well known issue on windows devices, sadly.

**Comment by N4N001** [comment]
Is this only for linux, or how do I use version 3 on windows? From what I see in the link it looks like linux thing.

**Comment by TudbuT** [comment]
Not quite a linux thing, I'm currently publishing the windows exe for it.

**Comment by N4N001** [comment]
Okay, thank you for your time and effort you've put into this <3

**Comment by TudbuT** [comment]
I'm almost done compiling it, expect the release in a few minutes!

**Comment by TudbuT** [comment]
There ya go!
